### ISSUE TITLE
How to flip the result floorplans to 3D model?

### ISSUE THREAD

**Issue by Hao-HUST** [woodfrog/floor-sp#10]
Hi, thanks for sharing your work.

I am wondering is that possible to flip the result floorplans to the 3D indoor model?

Thanks.

**Comment by woodfrog** [comment]
Hi, thanks for your interest.

I didn't try this but I think you can use a renderer to get a simple 3d indoor model: just assign a height for every reconstructed room of the floorplan (every room is just a polygon) and then plot all the rooms.

**Comment by Hao-HUST** [comment]
Thanks for responding.

Besides to the apartments, is that possible to extend your work to produce more complex floorplans, such as shopping mall or office building?

Thanks！

**Comment by woodfrog** [comment]
Hi,

If you can get the RGB-D scans of those complex buildings as well as some corresponding annotation data, you can re-train the whole system and get the results you want.  But If you were talking about directly using the pre-trained system on more complex buildings, I'm afraid that the room region estimation part could fail as there might be domain gaps between the original training data and the complex buildings.
