### ISSUE TITLE
open  unable to fill the data can i get the download links ? please

### ISSUE THREAD

**Issue by ravitejarj** [woodfrog/floor-sp#12]
unable to fill the data can I get the download links? please

**Comment by woodfrog** [comment]
Hi, you need to fill the form here [http://realsee.com/website/open/en](http://realsee.com/website/open/en), then Beike's system will send the data download links to your email.

**Comment by niravsculptsoft** [comment]
@woodfrog  need help as i am stuck i have try to download the data from your mention website but their submit button not working i am stuck please require help

**Comment by ogencoglu** [comment]
Yeah the link is dead

**Comment by woodfrog** [comment]
@ogencoglu  I have put two links in the readme, and the second one is still working ([http://realsee.com/open](http://realsee.com/open)). It's in Chinese but you can use a translator and read the form.
