### ISSUE TITLE
model cannot be opened

### ISSUE THREAD

**Issue by xuyongzhi** [woodfrog/floor-sp#5]
Thanks a lot for sharing the trained model! The model for "mask-rcnn" works well but the other two cannot be opened: corner_edge_module, room_corner_associate_module. Could you help check this? Thanks!

**Comment by woodfrog** [comment]
I guess you may not put the checkpoints in the proper directories? Those are just usual Pytorch checkpoints (i.e., dicts), so I don't understand what did you mean by "cannot be opened". Several other people told me that they run the whole pipeline successfully, so I guess the two files should be right. If you still can't make it after re-checking the doc, please provide more detailed error logs here.

**Comment by xuyongzhi** [comment]
Thanks for your prompt and detailed reply! I made a mistake and assumed that checkpoint_corner_edge_34.pth.tar has to be untared before using it as a checkpoint. All the models work fine.
