### ISSUE TITLE
Alignment issue between annotation and input for three scenes

### ISSUE THREAD

**Issue by xuyongzhi** [woodfrog/floor-sp#7]
The annotations and input images of three scenes seem to be unaligned:  ['7w6zvVsOBAQK4h4Bne7caQ', 'IDZkUGse-74FIy2OqM2u_Y', 'B9Abt6B78a0j2eRcygHjqC'] 
After running mask-rcnn/inference_corner.py, in the test_viz, I got:
![7w6zvVsOBAQK4h4Bne7caQ_maskrcnn_gt](https://github.com/xuyongzhi/floor-sp/blob/master/mask-rcnn/test_viz/10_7w6zvVsOBAQK4h4Bne7caQ_maskrcnn_gt.png) 
![7w6zvVsOBAQK4h4Bne7caQ_maskrcnn_input](https://github.com/xuyongzhi/floor-sp/blob/master/mask-rcnn/test_viz/10_7w6zvVsOBAQK4h4Bne7caQ_maskrcnn_input.png)

**Comment by woodfrog** [comment]
Yes, you are right. The camera parameter of several samples seems to be broken, which results in the wrong alignment, as you pointed out. We also noticed this problem when checking the 100 scenes. Beike re-processed the data before making it public to make sure that no privacy-related information is included - something might be accidentally messed up during the process. 

You can try to contact Beike's tech team to ask for the correct camera parameters for these three scenes. I think they would be happy to help. The email is available on their data page: http://realsee.com/website/open/en

**Comment by xuyongzhi** [comment]
Got it. Thank you so much!
